[package]
name = "sw"
version = "0.5.5"
edition = "2021"

[dependencies]
clap = { version = "4.5.58", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
rayon = "1.11.0"
