[package]
name = "sw"
version = "0.5.2"
edition = "2021"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
rayon = "1.11.0"
